export const NODE_STARTING_REGISTER = 1

export const NODE_ENDING_REGISTER = 56000

export const NODE_LED_START_REGISTER_NUMBER = 101

export const NODE_MODULES_FAULT_CODES_STARTING_REGISTER_NUMBER = 201

export const STARTING_REGISTER_NUMBER_FOR_MODULES = 1000

export const ENDING_REGISTER_NUMBER_FOR_MODULES = 30000

export const MINIMUM_REGISTER_COUNT_FOR_MODULES = 500

export const MINIMUM_ENCODING_NUMBER = 0

export const MAXIMUM_ENCODING_NUMBER_16_BITS = 65535

export const MAXIMUM_ENCODING_NUMBER_8_BITS = 255

export const MODULE_F_CODE_RESERVED_REGISTER_COUNT = 100

export const NODE_FAULT_CODE_REGISTER_NUMBER = 1

export const NODE_FAULT_INTERVAL_TIME_REGISTER: number = 2

export const NODE_FAULT_INTERVAL_UNIT_REGISTER = 3

export const NODE_MONITORING_FEATURE_INTERVAL_TIME_REGISTER = 4

export const NODE_MONITORING_FEATURE_INTERVAL_UNIT_REGISTER = 5

export const NODE_YEAR_REGISTER_NUMBER = 11

export const NODE_MONTH_REGISTER_NUMBER = 12

export const NODE_DAY_REGISTER_NUMBER = 13

export const NODE_HOUR_REGISTER_NUMBER = 14

export const NODE_MINUTE_REGISTER_NUMBER = 15

export const NODE_SECOND_REGISTER_NUMBER = 16

export const NODE_MILLI_SECOND_REGISTER_NUMBER = 17
